proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:50m
                 max_size=5g inactive=24h use_temp_path=off;

server {
  listen 8088;

  # кешируем статические файлы
  location /cdn/ {
    # /cdn/<bucket>/<key> -> http://minio:9000/<bucket>/<key>
    rewrite ^/cdn/(.*)$ /$1 break;

    proxy_pass http://minio:9000;

    proxy_cache cdn_cache;
    proxy_cache_valid 200 302 60m;
    proxy_cache_valid 404 1m;

    # важное: кеш-ключ = URI, у нас version в URI => инвалидация автоматом
    proxy_cache_key $scheme$proxy_host$request_uri;

    add_header X-Cache-Status $upstream_cache_status always;
  }
}